buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0'
        classpath 'org.jetbrains.compose:compose-gradle-plugin:1.7.1'
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
    project.ext.flutter = [
        compileSdkVersion: 35,
        targetSdkVersion: 35,
        minSdkVersion: 21,
        ndkVersion: "27.0.12077973"
    ]
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
